name: Publish Resume as PDF
run-name: Updating Resume PDF
on: push
  # push:
  #   branches:
  #     - 'main'
jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Build-Resume
        run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Release.txt
            resume.pdf