name: Publish Resume as PDF
run-name: Updating Resume PDF
on: push
  # push:
  #   branches:
  #     - 'main'
jobs:
  Publish-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get install xvfb
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm install
      - name: Build Resume
        run: npm run build
      - name: Update Tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: ./resume.pdf
          fail_on_unmatched_files: true
