name: Publish Resume as PDF
run-name: Updating Resume PDF
on: push
  # push:
  #   branches:
  #     - 'main'
jobs:
  Publish-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build Resume
        run: npm run build
      - name: Update Tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: resume.pdf